### ISSUE TITLE
error with npm start

### ISSUE THREAD

**Issue by ghost** [raf924/hack.chat-desktop#20]
when i try and start the program with npm start i get this error
spawn C:\Users\mattl\Desktop\hack.chat-desktop-master\hack.chat-desktop\node_modules\.bin\electron.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by raf924** [comment]
Full disclosure, I have no idea if the code, such as it is now, works. As you can see from the last commit, it's been a long while since I've worked on this. However in the log you sent me I can see something that can be corrected 

> C:\Users\mattl\Desktop\hack.chat-desktop-master\hack.chat-desktop\node_modules.bin\electron.cmd 
There seems to be a backward-slash missing between node_modules and .bin.

Also, since I've written no doc, as I was not expecting to share this before it was all ready and clean, you might not have known to run certain commands after npm install. For example, to install electron
```npm run install:electron```
and to install the required libraries for the front-end
```npm run postinstall```
Finally to run the project:
```npm run start```
You can find these commands in https://github.com/raf924/hack.chat-desktop/blob/master/package.json

**Comment by ghost** [comment]
ok, i'll wait for a more stable release then

**Comment by raf924** [comment]
I wouldn't do that if I were you. Basically this whole project should be put to pasture. I guess you could try and fix it up but if you want a desktop client for hack.chat, you really should just do it yourself.
